### ISSUE TITLE
Some issues since the refactoring. 

### ISSUE THREAD

**Issue by newca12** [siddhartha-gadgil/ProvingGround#140]
The recent refactoring is very welcome. Thanks.
I notice some issues and I just want to make sure that you are aware of them because CI does not spot them.

1. sbt mantle/test:run is broken
Simply need to modify iniCommands in built.sbt replacing import FansiShow._ by import translation.FansiShow._
2. pretty printing is broken since upgrade from PPrint 0.4 to 0.5
`
@ val Bool = "Boolean" :: Type
Bool: Typ[Term] with Subs[Typ[Term]] = SymbTyp(Name("Boolean"), 0)
`
[now configuration is different (via customizing the PPrint object instead of implicits) and I haven't written docs, but if you take a look you should be able to figure out how it works](https://gitter.im/lihaoyi/PPrint?at=5919e8319f4f4ab05bc88269) 
3. sbt server/run is broken
`
[info] Running provingground.ScriptServer
[error] (run-main-0) java.lang.NoSuchMethodError: coursier.maven.MavenRepository$.apply$default$5()Lscala/collection/immutable/Set;
java.lang.NoSuchMethodError: coursier.maven.MavenRepository$.apply$default$5()Lscala/collection/immutable/Set;
`
This look like a Scala compat issue (similar to https://github.com/coursier/coursier/issues/464)

**Comment by siddhartha-gadgil** [comment]
Thanks a lot. I had missed these regressions. I will work on them.

**Comment by siddhartha-gadgil** [comment]
Looks like there are two changes in ammonite:
(1) Unicode is escaped
(2) Objects with toString overridden are still printed in the structured
form - this used to happen, then changed in an earlier method of ammonite.

I will look at the documentation to investigate all these.

**Comment by siddhartha-gadgil** [comment]
* Looks like the pretty printing  is fixed - it now uses  `fansi`.
* The `server/run` uses _Ammonite Kernel_ causing version compatibility issues after upgrade; it seems best to use ammonite directly running with a synthetic `InputStream` and `OutputStream`.

**Comment by newca12** [comment]
LGTM
Still very minor difference like this
Cons(Name("0"), IdShape(), Cons(Name("succ"),...
vs Cons(0,IdShape(),Cons(succ,...

Example :
`@ val NatInd = ("0" ::: Nat) |: ("succ" ::: Nat -->>: Nat) =: Nat
NatInd: ConstructorSeqTL[HNil :: ConstructorShape.FuncConsShape.type :: HNil :: HNil, Term, Term :: Func[Term, Term] :: HNil] = ConstructorSeqTL( 
  Cons(Name("0"), IdShape(), Cons(Name("succ"), FuncConsShape(IdIterShape(), IdShape()), Empty())),
  Nat : 𝒰 _0`
instead of
`@ val NatInd = ("0" ::: Nat) |: ("succ" ::: Nat -->>: Nat) =: Nat
NatInd: ConstructorSeqTL[HNil :: ConstructorShape.FuncConsShape.type :: HNil :: HNil, Term, Term 
:: Func[Term, Term] :: HNil] = ConstructorSeqTL( 
  Cons(0,IdShape(),Cons(succ,FuncConsShape(IdIterShape(),IdShape()),Empty())), Nat : 𝒰 _0)`

**Comment by siddhartha-gadgil** [comment]
That change is fixed too.
